import {
    Card,
    CardMedia,
    CardContent,
    CardActions,
    Typography,
    Button,
  } from "@material-ui/core";
  import Head from "next/head";
  import styles from "../../styles/Home.module.css";
  import { Product, products } from "../../model";
  

  export default function ProductDetailPage() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Listagem de produtos</title>
          {/* <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" /> */}
        </Head>
  
        <Typography component="h1" variant="h3" color="textPrimary" gutterBottom>
          Produtos
        </Typography>
        {products.map((product, key) => (
          <Card key={key}>
            <CardMedia image={product.image_url} />
            <CardContent>
              <Typography component="h2" variant="h5" gutterBottom>
                {product.name}
              </Typography>
            </CardContent>
            <CardActions>
              <Button size="small" color="primary" component="a">Detalhes</Button>
            </CardActions>
          </Card>
        ))}
      </div>
    );
  }
  